baseURL = 'https://trente.gelovenleren.net/'
languageCode = 'nl'
title = 'Catechismus van het Concilie van Trente'
theme = 'hugo-book'
googleAnalytics = 'G-PN0L113EB0'

[menu]
  # [before] []
[[menu.after]]
  name = "Geloven Leren"
  url = "https://gelovenleren.net"
  weight = 10

[params]
  BookSearch = true
  BookSection = "*"
