#!/bin/bash
# build the website (1st run)
./hugo
# build the calendar files
cd calendar
ant
# build the website (2nd run - need another run, to move the json files from static to public)
cd ..
./hugo 
# uplod the website 
cd public
if [ ! -f "404.html" ]; then
  echo "This doesn't seem to be a valid public folder; exiting"
  exit
fi
rsync -aP ./ vps@37.97.145.69:/var/www/trente.gelovenleren.net --delete
